# Site settings
title: Ideas to Classes Actions to Functions Words to Variables
header-img: img/home-bg.png
email: omikolaj1@gmail.com
copyright_name: omikolaj
description: > # this means to ignore newlines until "baseurl:"
  Coding.Troubleshooting.Learning("It worked!!!"); 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  omikolaj
learn_profile: omikolaj
email_username: omikolaj1@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
